export const CUSTOMER_REGISTER_REQUEST = 'CUSTOMER_REGISTER_REQUEST';
export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS';
export const CUSTOMER_REGISTER_FAIL = 'CUSTOMER_REGISTER_FAIL';

export const CUSTOMER_SIGNIN_REQUEST = 'CUSTOMER_SIGNIN_REQUEST';
export const CUSTOMER_SIGNIN_SUCCESS = 'CUSTOMER_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const CUSTOMER_SIGNIN_FAIL = 'CUSTOMER_SIGNIN_FAIL';

export const CUSTOMER_SIGNOUT = 'CUSTOMER_SIGNOUT';
export const CUSTOMER_UPDATE_PROFILE_RESET ="CUSTOMER_UPDATE_PROFILE_RESET"

export const CUSTOMER_DETAILS_FAIL = "CUSTOMER_DETAILS_FAIL"
export const CUSTOMER_DETAILS_REQUEST = "CUSTOMER_DETAILS_REQUEST"
export const CUSTOMER_DETAILS_SUCCESS = " CUSTOMER_DETAILS_SUCCESS"
export const CUSTOMER_UPDATE_PROFILE_FAIL = " CUSTOMER_UPDATE_PROFILE_FAIL"
export const CUSTOMER_UPDATE_PROFILE_REQUEST = " CUSTOMER_UPDATE_PROFILE_REQUEST"
export const CUSTOMER_UPDATE_PROFILE_SUCCESS = "CUSTOMER_UPDATE_PROFILE_SUCCESS"


export const PRODUCTS_SEARCH_BY_NAME="PRODUCTS_SEARCH_BY_NAME"
export const PRODUCTS_SEARCH_BY_CATEGORY="PRODUCTS_SEARCH_BY_CATEGORY"
export const PRODUCTS_SEARCH_BY_BRAND="PRODUCTS_SEARCH_BY_BRAND"
export const PRODUCTS_SEARCH_BY_RATING="PRODUCTS_SEARCH_BY_RATING"


export const CUSTOMER_PRODUCTS_SORT_BY_NAMED = "CUSTOMER_PRODUCTS_SORT_BY_NAMED"
export const CUSTOMER_PRODUCTS_SORT_BY_NAMEA = "CUSTOMER_PRODUCTS_SORT_BY_NAMEA"
export const CUSTOMER_PRODUCTS_SORT_BY_PRICED = "CUSTOMER_PRODUCTS_SORT_BY_PRICED"
export const CUSTOMER_PRODUCTS_SORT_BY_PRICEA = "CUSTOMER_PRODUCTS_SORT_BY_PRICEA"
export const CUSTOMER_PRODUCTS_SORT_BY_RATINGD = "CUSTOMER_PRODUCTS_SORT_BY_RATINGD"
export const CUSTOMER_PRODUCTS_SORT_BY_RATINGA = "CUSTOMER_PRODUCTS_SORT_BY_RATINGA"