  
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';


export const REQUEST_PRODUCT_ADD_REQUEST = 'REQUEST_PRODUCT_ADD_REQUEST';
export const REQUEST_PRODUCT_ADD_SUCCESS = 'REQUEST_PRODUCT_ADD_SUCCESS';
export const REQUEST_PRODUCT_ADD_FAIL = 'REQUEST_PRODUCT_ADD_FAIL';


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_UPDATE_CHOSEN_SUCCESS = 'PRODUCT_UPDATE_CHOSEN_SUCCESS';
export const PRODUCT_UPDATE_CHOSEN_REQUEST= "PRODUCT_UPDATE_CHOSEN_REQUEST";
export const PRODUCT_UPDATE_CHOSEN_FAIL="PRODUCT_UPDATE_CHOSEN_FAIL";

export const CUSTOMER_PRODUCT_LIST_REQUEST = 'CUSTOMER_PRODUCT_LIST_REQUEST';
export const CUSTOMER_PRODUCT_LIST_SUCCESS = 'CUSTOMER_PRODUCT_LIST_SUCCESS';
export const CUSTOMER_PRODUCT_LIST_FAIL = 'CUSTOMER_PRODUCT_LIST_FAIL';


export const REQUESTED_PRODUCT_LIST_REQUEST = 'REQUESTED_PRODUCT_LIST_REQUEST';
export const REQUESTED_PRODUCT_LIST_SUCCESS = 'REQUESTED_PRODUCT_LIST_SUCCESS';
export const REQUESTED_PRODUCT_LIST_FAIL = 'REQUESTED_PRODUCT_LIST_FAIL';

export const PRODUCT_SEARCH_REQUEST="PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS="PRODUCT_SEARCH_SUCCESS"
export const PRODUCT_SEARCH_FAIL="PRODUCT_SEARCH_FAIL";


export const PRODUCT_SEARCH_BY_OPTION_REQUEST ="PRODUCT_SEARCH_BY_OPTION_REQUEST";
export const PRODUCT_SEARCH_BY_OPTION_SUCCESS ="PRODUCT_SEARCH_BY_OPTION_SUCCESS";
export const PRODUCT_SEARCH_BY_OPTION_FAIL = "PRODUCT_SEARCH_BY_OPTION_FAIL";

export const SEARCH_STATUS="SEARCH_STATUS"


export const PRODUCTS_SORT_BY_NAMED="PRODUCTS_SORT_BY_NAMED"
export const PRODUCTS_SORT_BY_NAMEA="PRODUCTS_SORT_BY_NAMEA"
export const PRODUCTS_SORT_BY_PRICED="PRODUCTS_SORT_BY_PRICED"
export const PRODUCTS_SORT_BY_PRICEA="PRODUCTS_SORT_BY_PRICEA"
export const PRODUCTS_SORT_BY_RATINGD="PRODUCTS_SORT_BY_RATINGD"
export const PRODUCTS_SORT_BY_RATINGA="PRODUCTS_SORT_BY_RATINGA"